spring:
  datasource:
    password: jjzboy45
    url: jdbc:mysql://localhost:3306/webAppDB?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

